# Generated by Django 2.1.8 on 2020-09-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filer',
            name='size',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='filer',
            name='title',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
