# Generated by Django 2.1.8 on 2022-01-27 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
