# Generated by Django 2.1.8 on 2022-02-20 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antik_fup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.CharField(max_length=100)),
                ('download', models.CharField(max_length=100)),
                ('upload', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
