# Generated by Django 2.1.8 on 2022-02-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20220220_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antik_fup',
            options={'ordering': ('-date',)},
        ),
    ]
