# Generated by Django 2.1.8 on 2022-05-07 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20220220_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=100)),
                ('time', models.DateField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
