# Generated by Django 2.1.8 on 2022-05-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
