# Generated by Django 2.1.8 on 2022-05-07 17:11

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_meeting_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('data', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
