# Generated by Django 2.1.8 on 2020-10-04 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('broadband', models.FloatField()),
                ('infrared', models.FloatField()),
                ('light', models.FloatField()),
                ('temprpi', models.FloatField()),
                ('temproom', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
