# Generated by Django 2.1.8 on 2020-10-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='cpu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='mem',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='temp',
            field=models.FloatField(),
        ),
    ]
